Configuration
pirc25/Hello-Microverse pull request #2
Opened 2022-04-21 15:49 UTC by pirc25

2022-04-21 16:32 UTC, Danieldotcomcoder requested changes
Hello @pirc25, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

- Linters are setup correctly ✔✔
- Clear and nice code ✔✔
- All Linters are passing ✔✔

## Required Changes ♻️

- Please add a descriptive Pull Request message with a title and mention the features that you implemented in a short summary. 😃✔✔


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-04-21 21:43 UTC, youmari requested changes
Hi @pirc25 , 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes

- [ ] please try to change the short summary as the previous reviewer asked you 
for example you can say : `Add HTML file white h1 header` and so on 
- [ ] [OPTIONAL] please try next time  to capitalize your commits as in the professional rules

_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-04-21 21:43 UTC, youmari commented on .gitignore
> +.stylelintrc.json
- [ ] [OPTIONAL] please you should remove this file from the `.gitignore` file cause this file is the linter for CSS

2022-04-21 21:43 UTC, youmari commented on README.md
> +
- [ ] [OPTIONAL] it would be the best to add a `Getting started` header with how can someone use your project

2022-04-23 18:12 UTC, smunozmo approved these changes
Hi @pirc25, 👋 

## Highlights 👏 

- Great work using the right GitHub Flow.
- Your README looks professional, well done!
- Commits are descriptive, good work.
- Linters are working properly, great job!

Your project is complete!  There is nothing else to say other than... it's time to merge it! 🚀 
Very nice work, congratulations! 🎉 

### APPROVED! 💯  💯  💯 

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>


Cheers and Happy coding! 🤓 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-23 18:30 UTC, merged

2022-04-23 18:31 UTC, pirc25 commented
I merged two branches with linters configuration.